#!/usr/bin/env node
// Test double for a generator CLI (claude/codex). Ignores its argv flags,
// reads the engineered prompt from stdin, and prints a deterministic agent
// definition to stdout — wrapped in a code fence to exercise fence stripping.
let input = "";
process.stdin.setEncoding("utf8");
process.stdin.on("data", (d) => {
  input += d;
});
process.stdin.on("end", () => {
  // Emit a couple of progress-ish lines to stderr (streamed as logs).
  process.stderr.write("thinking...\n");
  const body = [
    "```markdown",
    "---",
    "name: test-agent",
    "description: A test agent generated by the fake CLI.",
    "model: sonnet",
    "---",
    "",
    "You are a test agent. The prompt length was " + input.length + " chars.",
    "```",
  ].join("\n");
  process.stdout.write(body + "\n");
  process.exit(0);
});
