import { useCallback, useRef, useState } from "react";
import { Moon, PenLine, Sun } from "lucide-react";
import type {
  DoneEvent,
  ErrorEvent as GenErrorEvent,
  GenerateRequest,
  JobStage,
  JobState,
  LogEvent,
} from "@nightwriter/shared";
import { Button } from "@/components/ui/button";
import { PromptForm } from "@/components/PromptForm";
import { RunView } from "@/components/RunView";
import { cancelJob, startGeneration, streamJob } from "@/lib/api";

interface RunState {
  jobId: string;
  state: JobState;
  stage: JobStage;
  logs: LogEvent[];
  done?: DoneEvent;
  error?: GenErrorEvent;
}

export default function App() {
  const [run, setRun] = useState<RunState | null>(null);
  const [submitError, setSubmitError] = useState<string | null>(null);
  const [dark, setDark] = useState(true);
  const closeRef = useRef<(() => void) | null>(null);

  const toggleTheme = () => {
    const next = !dark;
    setDark(next);
    document.documentElement.classList.toggle("dark", next);
  };

  const handleSubmit = useCallback(async (req: GenerateRequest) => {
    setSubmitError(null);
    try {
      const { jobId } = await startGeneration(req);
      setRun({ jobId, state: "queued", stage: "queued", logs: [] });
      closeRef.current = streamJob(jobId, {
        onStatus: (e) =>
          setRun((r) =>
            r ? { ...r, state: e.state, stage: e.stage } : r,
          ),
        onLog: (e) =>
          setRun((r) => (r ? { ...r, logs: [...r.logs, e] } : r)),
        onDone: (e) =>
          setRun((r) =>
            r ? { ...r, done: e, state: "succeeded", stage: "ready" } : r,
          ),
        onError: (e) =>
          setRun((r) =>
            r
              ? {
                  ...r,
                  error: e,
                  state: e.code === "canceled" ? "canceled" : "failed",
                  stage: "error",
                }
              : r,
          ),
        onConnectionError: () =>
          setRun((r) =>
            r && r.state !== "succeeded"
              ? {
                  ...r,
                  error: {
                    code: "internal",
                    message: "Lost connection to the server.",
                  },
                  state: "failed",
                  stage: "error",
                }
              : r,
          ),
      });
    } catch (err) {
      setSubmitError(err instanceof Error ? err.message : String(err));
    }
  }, []);

  const handleCancel = useCallback(() => {
    if (run) void cancelJob(run.jobId);
  }, [run]);

  const handleReset = useCallback(() => {
    closeRef.current?.();
    closeRef.current = null;
    setRun(null);
    setSubmitError(null);
  }, []);

  const busy = run?.state === "queued" || run?.state === "running";

  return (
    <div className="min-h-screen bg-background text-foreground">
      <header className="border-b border-border">
        <div className="container flex h-12 items-center justify-between">
          <div className="flex items-center gap-2">
            <PenLine className="size-4 text-primary" />
            <span className="text-sm font-semibold">Nightwriter</span>
            <span className="text-[11px] text-muted-foreground">
              agent definition generator
            </span>
          </div>
          <Button size="sm" variant="ghost" onClick={toggleTheme}>
            {dark ? <Sun /> : <Moon />}
          </Button>
        </div>
      </header>

      <main className="container max-w-3xl space-y-4 py-6">
        {!run && (
          <>
            <PromptForm disabled={false} onSubmit={handleSubmit} />
            {submitError && (
              <p className="text-xs text-destructive">{submitError}</p>
            )}
          </>
        )}

        {run && (
          <RunView
            jobId={run.jobId}
            state={run.state}
            stage={run.stage}
            logs={run.logs}
            done={run.done}
            error={run.error}
            onCancel={handleCancel}
            onReset={handleReset}
          />
        )}

        {run && !busy && (
          <p className="text-center text-[11px] text-muted-foreground">
            Generated by Nightwriter — definitions are produced by a real CLI
            subprocess in an isolated workspace.
          </p>
        )}
      </main>
    </div>
  );
}
