import type { TargetSpec } from "./factory.js";

/** Claude Code subagent: markdown with YAML frontmatter under .claude/agents/. */
const claude: TargetSpec = {
  id: "claude",
  displayName: "Claude Code",
  formatInstructions: `The file is Markdown with YAML frontmatter:
---
name: <kebab-case-name>
description: <one sentence describing when to use this agent>
tools: Read, Edit, Bash, Grep   # comma-separated, or omit to inherit all
model: sonnet                    # haiku | sonnet | opus
---

<System prompt body in Markdown: role, responsibilities, step-by-step
operating procedure, and constraints. Be specific and actionable.>`,
  definitionFile: "agent.md",
  installScript: (ctx) => `# Install the subagent into a project's .claude/agents/.
# Usage: bash install.sh [project-dir]   (defaults to the current directory)
DEST="\${1:-$PWD}/.claude/agents"
mkdir -p "$DEST"
cp "$HERE/agent.md" "$DEST/${ctx.slug}.md"
echo "Installed ${ctx.slug}.md to $DEST/"
echo "Restart Claude Code or run /agents to pick it up."`,
  activationGuide: (ctx) => `# ${ctx.slug} — Claude Code subagent

Generated by Nightwriter from the prompt:

> ${ctx.userPrompt.trim()}

The definition is **\`agent.md\`** in this folder.

## Install
\`\`\`bash
bash install.sh            # installs into ./.claude/agents/
bash install.sh /path/to/project   # or target another project
\`\`\`
This copies \`agent.md\` to \`<project>/.claude/agents/${ctx.slug}.md\`.

## Activate
- Open Claude Code in the project and run \`/agents\` to confirm it loaded.
- For user-wide availability, copy \`agent.md\` to \`~/.claude/agents/${ctx.slug}.md\`.
`,
};

/** Codex / AGENTS.md style agent guidance. */
const codex: TargetSpec = {
  id: "codex",
  displayName: "Codex CLI",
  formatInstructions: `The file is Markdown (AGENTS.md style) describing the agent's
operating contract for the Codex CLI:
# <Agent Name>
## Role
## Capabilities
## Operating procedure   (numbered steps)
## Constraints / guardrails
## Tools & commands       (allowed shell commands, if any)
Be concrete and imperative.`,
  definitionFile: "agent.md",
  installScript: (ctx) => `# Install the agent definition into a project's .codex/agents/.
# Usage: bash install.sh [project-dir]   (defaults to the current directory)
DEST="\${1:-$PWD}/.codex/agents"
mkdir -p "$DEST"
cp "$HERE/agent.md" "$DEST/${ctx.slug}.md"
echo "Installed ${ctx.slug}.md to $DEST/"
echo "Reference it from your project's AGENTS.md or pass it to 'codex exec'."`,
  activationGuide: (ctx) => `# ${ctx.slug} — Codex agent

Generated by Nightwriter from the prompt:

> ${ctx.userPrompt.trim()}

The definition is **\`agent.md\`** in this folder.

## Install
\`\`\`bash
bash install.sh            # installs into ./.codex/agents/
\`\`\`
Copies \`agent.md\` to \`<project>/.codex/agents/${ctx.slug}.md\`.

## Activate
- Add a link to it from your top-level \`AGENTS.md\`, or
- Feed it as context: \`cat agent.md | codex exec -\`.
`,
};

/** OpenClaw runtime: markdown system prompt. */
const openclaw: TargetSpec = {
  id: "openclaw",
  displayName: "OpenClaw",
  formatInstructions: `The file is a single Markdown document with this structure:
# <Agent Name>
## Description
## System Prompt
<the full system prompt>
## Tools
- <tool name>: <what it does>
## Examples
<one or two usage examples>`,
  definitionFile: "agent.md",
  installScript: (ctx) => `# Install the OpenClaw agent.
DEST="\${OPENCLAW_HOME:-$HOME/.openclaw}/agents"
mkdir -p "$DEST"
cp "$HERE/agent.md" "$DEST/${ctx.slug}.agent.md"
echo "Installed ${ctx.slug} to $DEST/"
echo "Run 'openclaw agents' to verify, then 'openclaw run ${ctx.slug}'."`,
  activationGuide: (ctx) => `# ${ctx.slug} — OpenClaw agent

Generated by Nightwriter from the prompt:

> ${ctx.userPrompt.trim()}

The definition is **\`agent.md\`** in this folder.

## Install
\`\`\`bash
bash install.sh
\`\`\`
Copies \`agent.md\` to \`$OPENCLAW_HOME/agents/${ctx.slug}.agent.md\` (defaults to \`~/.openclaw\`).

## Activate
\`\`\`bash
openclaw agents            # confirm it is listed
openclaw run ${ctx.slug}   # start the agent
\`\`\`
`,
};

/** Hermes runtime: YAML agent manifest. */
const hermes: TargetSpec = {
  id: "hermes",
  displayName: "Hermes",
  formatInstructions: `The file is YAML:
name: <kebab-case-name>
description: <one sentence>
model: <model id>
system_prompt: |
  <multi-line system prompt>
tools:
  - name: <tool>
    description: <what it does>
Keep it valid YAML with 2-space indentation.`,
  definitionFile: "agent.yaml",
  installScript: (ctx) => `# Install the Hermes agent manifest.
DEST="\${HERMES_HOME:-$HOME/.hermes}/agents"
mkdir -p "$DEST"
cp "$HERE/agent.yaml" "$DEST/${ctx.slug}.agent.yaml"
echo "Installed ${ctx.slug} to $DEST/"
echo "Run 'hermes load ${ctx.slug}' to activate."`,
  activationGuide: (ctx) => `# ${ctx.slug} — Hermes agent

Generated by Nightwriter from the prompt:

> ${ctx.userPrompt.trim()}

The definition is **\`agent.yaml\`** in this folder.

## Install
\`\`\`bash
bash install.sh
\`\`\`
Copies \`agent.yaml\` to \`$HERMES_HOME/agents/${ctx.slug}.agent.yaml\` (defaults to \`~/.hermes\`).

## Activate
\`\`\`bash
hermes load ${ctx.slug}
hermes run ${ctx.slug}
\`\`\`
`,
};

/** Google ADK: Python agent.py installed into a package + venv. */
const adk: TargetSpec = {
  id: "adk",
  displayName: "Google ADK",
  formatInstructions: `The file is Python for the Google Agent Development Kit (ADK).
Define a module-level variable named root_agent:

from google.adk.agents import Agent

root_agent = Agent(
    name="<snake_case_name>",
    model="<model id, e.g. gemini-2.0-flash>",
    description="<one sentence>",
    instruction="""<the system prompt / instructions>""",
    tools=[],
)

Output only valid Python.`,
  definitionFile: "agent.py",
  installScript: (ctx) => {
    const pkg = toSnake(ctx.slug);
    return `# Build the ADK package from agent.py and set up a venv.
PKG="${pkg}"
mkdir -p "$PKG"
cp "$HERE/agent.py" "$PKG/agent.py"
printf 'from . import agent\\n' > "$PKG/__init__.py"
python3 -m venv .venv
source .venv/bin/activate
pip install --upgrade pip
pip install -r "$HERE/requirements.txt"
echo "Installed. Run the agent with:"
echo "  source .venv/bin/activate && adk run $PKG"`;
  },
  activationGuide: (ctx) => {
    const pkg = toSnake(ctx.slug);
    return `# ${pkg} — Google ADK agent

Generated by Nightwriter from the prompt:

> ${ctx.userPrompt.trim()}

The definition is **\`agent.py\`** in this folder.

## Install
\`\`\`bash
bash install.sh
\`\`\`
Builds the \`${pkg}/\` package from \`agent.py\`, then creates a venv and installs \`google-adk\`.

## Activate
\`\`\`bash
source .venv/bin/activate
adk run ${pkg}        # or: adk web  for the dev UI
\`\`\`
Set provider credentials (e.g. \`GOOGLE_API_KEY\`) in your environment first.
`;
  },
  extraFiles: () => [
    { path: "requirements.txt", content: "google-adk>=0.1.0\n" },
  ],
};

function toSnake(slug: string): string {
  return slug.replace(/-/g, "_");
}

export const TARGET_SPECS: TargetSpec[] = [
  claude,
  codex,
  openclaw,
  hermes,
  adk,
];
