import type { TargetSpec } from "./factory.js";

/** Claude Code subagent: markdown with YAML frontmatter under .claude/agents/. */
const claude: TargetSpec = {
  id: "claude",
  displayName: "Claude Code",
  formatInstructions: `The file is Markdown with YAML frontmatter:
---
name: <kebab-case-name>
description: <one sentence describing when to use this agent>
tools: Read, Edit, Bash, Grep   # comma-separated, or omit to inherit all
model: sonnet                    # haiku | sonnet | opus
---

<System prompt body in Markdown: role, responsibilities, step-by-step
operating procedure, and constraints. Be specific and actionable.>`,
  definitionPath: (slug) => `.claude/agents/${slug}.md`,
  installScript: (_ctx, defPath) => `# Install the subagent into the current project.
DEST=".claude/agents"
mkdir -p "$DEST"
cp "${defPath}" "$DEST/"
echo "Installed $(basename "${defPath}") to $DEST/"
echo "Restart Claude Code or run /agents to pick it up."`,
  activationGuide: (ctx, defPath) => `# ${ctx.slug} — Claude Code subagent

Generated by Nightwriter from the prompt:

> ${ctx.userPrompt.trim()}

## Install
\`\`\`bash
bash install.sh
\`\`\`
This copies \`${defPath}\` into your project's \`.claude/agents/\` directory.

## Activate
- Open Claude Code in the project and run \`/agents\` to confirm it loaded.
- Invoke it with the Task tool or by asking Claude to delegate to the agent by name.
- For user-wide availability, copy the file to \`~/.claude/agents/\` instead.
`,
};

/** Codex / AGENTS.md style agent guidance. */
const codex: TargetSpec = {
  id: "codex",
  displayName: "Codex CLI",
  formatInstructions: `The file is Markdown (AGENTS.md style) describing the agent's
operating contract for the Codex CLI:
# <Agent Name>
## Role
## Capabilities
## Operating procedure   (numbered steps)
## Constraints / guardrails
## Tools & commands       (allowed shell commands, if any)
Be concrete and imperative.`,
  definitionPath: (slug) => `.codex/agents/${slug}.md`,
  installScript: (_ctx, defPath) => `# Install the agent definition for the Codex CLI.
DEST=".codex/agents"
mkdir -p "$DEST"
cp "${defPath}" "$DEST/"
echo "Installed $(basename "${defPath}") to $DEST/"
echo "Reference it from your project's AGENTS.md or pass it to 'codex exec'."`,
  activationGuide: (ctx, defPath) => `# ${ctx.slug} — Codex agent

Generated by Nightwriter from the prompt:

> ${ctx.userPrompt.trim()}

## Install
\`\`\`bash
bash install.sh
\`\`\`
Copies \`${defPath}\` into \`.codex/agents/\`.

## Activate
- Add a link to this file from your top-level \`AGENTS.md\`, or
- Feed it as context: \`cat ${defPath} | codex exec -\`.
`,
};

/** OpenClaw runtime: JSON manifest + markdown system prompt. */
const openclaw: TargetSpec = {
  id: "openclaw",
  displayName: "OpenClaw",
  formatInstructions: `The file is a single Markdown document with this structure:
# <Agent Name>
## Description
## System Prompt
<the full system prompt>
## Tools
- <tool name>: <what it does>
## Examples
<one or two usage examples>`,
  definitionPath: (slug) => `openclaw/${slug}.agent.md`,
  installScript: (ctx, defPath) => `# Install the OpenClaw agent.
DEST="$\{OPENCLAW_HOME:-$HOME/.openclaw}/agents"
mkdir -p "$DEST"
cp "${defPath}" "$DEST/${ctx.slug}.agent.md"
echo "Installed ${ctx.slug} to $DEST/"
echo "Run 'openclaw agents' to verify, then 'openclaw run ${ctx.slug}'."`,
  activationGuide: (ctx, defPath) => `# ${ctx.slug} — OpenClaw agent

Generated by Nightwriter from the prompt:

> ${ctx.userPrompt.trim()}

## Install
\`\`\`bash
bash install.sh
\`\`\`
Installs \`${defPath}\` into \`$OPENCLAW_HOME/agents\` (defaults to \`~/.openclaw/agents\`).

## Activate
\`\`\`bash
openclaw agents            # confirm it is listed
openclaw run ${ctx.slug}   # start the agent
\`\`\`
`,
};

/** Hermes runtime: YAML agent manifest. */
const hermes: TargetSpec = {
  id: "hermes",
  displayName: "Hermes",
  formatInstructions: `The file is YAML:
name: <kebab-case-name>
description: <one sentence>
model: <model id>
system_prompt: |
  <multi-line system prompt>
tools:
  - name: <tool>
    description: <what it does>
Keep it valid YAML with 2-space indentation.`,
  definitionPath: (slug) => `hermes/${slug}.agent.yaml`,
  installScript: (ctx, defPath) => `# Install the Hermes agent manifest.
DEST="$\{HERMES_HOME:-$HOME/.hermes}/agents"
mkdir -p "$DEST"
cp "${defPath}" "$DEST/${ctx.slug}.agent.yaml"
echo "Installed ${ctx.slug} to $DEST/"
echo "Run 'hermes load ${ctx.slug}' to activate."`,
  activationGuide: (ctx, defPath) => `# ${ctx.slug} — Hermes agent

Generated by Nightwriter from the prompt:

> ${ctx.userPrompt.trim()}

## Install
\`\`\`bash
bash install.sh
\`\`\`
Installs \`${defPath}\` into \`$HERMES_HOME/agents\` (defaults to \`~/.hermes/agents\`).

## Activate
\`\`\`bash
hermes load ${ctx.slug}
hermes run ${ctx.slug}
\`\`\`
`,
};

/** Google ADK: Python package defining root_agent. */
const adk: TargetSpec = {
  id: "adk",
  displayName: "Google ADK",
  formatInstructions: `The file is Python for the Google Agent Development Kit (ADK).
Define a module-level variable named root_agent:

from google.adk.agents import Agent

root_agent = Agent(
    name="<snake_case_name>",
    model="<model id, e.g. gemini-2.0-flash>",
    description="<one sentence>",
    instruction="""<the system prompt / instructions>""",
    tools=[],
)

Output only valid Python.`,
  definitionPath: (slug) => `${toSnake(slug)}/agent.py`,
  installScript: (ctx) => {
    const pkg = toSnake(ctx.slug);
    return `# Set up a Python venv and install the ADK agent package.
python3 -m venv .venv
source .venv/bin/activate
pip install --upgrade pip
pip install -r requirements.txt
echo "Installed. Run the agent with:"
echo "  source .venv/bin/activate && adk run ${pkg}"`;
  },
  activationGuide: (ctx, defPath) => {
    const pkg = toSnake(ctx.slug);
    return `# ${pkg} — Google ADK agent

Generated by Nightwriter from the prompt:

> ${ctx.userPrompt.trim()}

## Install
\`\`\`bash
bash install.sh
\`\`\`
Creates a virtualenv and installs \`google-adk\`. Definition lives at \`${defPath}\`.

## Activate
\`\`\`bash
source .venv/bin/activate
adk run ${pkg}        # or: adk web  for the dev UI
\`\`\`
Set provider credentials (e.g. \`GOOGLE_API_KEY\`) in your environment first.
`;
  },
  extraFiles: (ctx) => {
    const pkg = toSnake(ctx.slug);
    return [
      { path: `${pkg}/__init__.py`, content: "from . import agent\n" },
      { path: "requirements.txt", content: "google-adk>=0.1.0\n" },
    ];
  },
};

function toSnake(slug: string): string {
  return slug.replace(/-/g, "_");
}

export const TARGET_SPECS: TargetSpec[] = [
  claude,
  codex,
  openclaw,
  hermes,
  adk,
];
