import type { ArtifactFile } from "./types.js";
import type { TargetSpec } from "./factory.js";

/* --------------------------------------------------------------------------
 * Target formats are modeled on the real runtimes:
 * - claude  : Claude Code subagent — .claude/agents/<name>.md (md + frontmatter)
 * - codex   : Codex subagent — .codex/agents/<name>.toml (TOML)
 * - openclaw: OpenClaw agent workspace — a dir of AGENTS.md/SOUL.md/… + skills/
 * - hermes  : Hermes Agent skill — ~/.hermes/skills/<name>/SKILL.md (agentskills.io)
 * - adk     : Google ADK — a Python package (__init__.py + agent.py: root_agent)
 * -------------------------------------------------------------------------- */

/** Claude Code subagent: markdown with YAML frontmatter under .claude/agents/. */
const claude: TargetSpec = {
  id: "claude",
  displayName: "Claude Code",
  formatInstructions: `The file is Markdown with YAML frontmatter:
---
name: <kebab-case-name>
description: <one sentence describing when to use this agent>
tools: Read, Edit, Bash, Grep   # comma-separated, or omit to inherit all
model: sonnet                    # haiku | sonnet | opus | inherit
---

<System prompt body in Markdown: role, responsibilities, a step-by-step
operating procedure, and constraints. Be specific and actionable.>`,
  definitionFile: "agent.md",
  // Claude Code invokes a subagent by its frontmatter `name`, not the filename.
  // Pin it to the slug so the name users call matches the file/zip/guide.
  normalizeDefinition: (def, ctx) => setFrontmatterName(def, ctx.slug),
  installScript: (ctx) => `# Install the subagent into a project's .claude/agents/.
# Usage: bash install.sh [project-dir]   (defaults to the current directory)
DEST="\${1:-$PWD}/.claude/agents"
mkdir -p "$DEST"
install_file "$HERE/agent.md" "$DEST/${ctx.slug}.md"
echo "Installed ${ctx.slug}.md to $DEST/"
echo "Restart Claude Code or run /agents to pick it up."`,
  activationGuide: (ctx) => `# ${ctx.slug} — Claude Code subagent

Generated by Nightwriter from the prompt:

> ${ctx.userPrompt.trim()}

The definition is **\`agent.md\`** (Markdown + YAML frontmatter).

## Install
\`\`\`bash
bash install.sh                    # into ./.claude/agents/
bash install.sh /path/to/project   # or another project
\`\`\`
Copies \`agent.md\` to \`<project>/.claude/agents/${ctx.slug}.md\`. For user-wide
use, copy it to \`~/.claude/agents/${ctx.slug}.md\` instead.

## Activate
Run \`/agents\` in Claude Code to confirm it loaded, then delegate to it by its
\`name\` — which Nightwriter pins to **\`${ctx.slug}\`** (the frontmatter \`name:\`
in \`agent.md\`, not the filename).
`,
};

/** Codex subagent: a TOML file under .codex/agents/. */
const codex: TargetSpec = {
  id: "codex",
  displayName: "Codex CLI",
  formatInstructions: `The file is TOML for a Codex subagent. Required keys:
name = "<kebab-case-name>"
description = "<one sentence: when to use this agent>"
developer_instructions = """
<the full system prompt / operating instructions, multi-line>
"""

Optional keys (include only if useful):
model = "gpt-5.4"               # the user may change this to a model they have
model_reasoning_effort = "high" # minimal | low | medium | high
sandbox_mode = "read-only"      # read-only | workspace-write | danger-full-access

Output ONLY valid TOML. Use triple-quoted strings for multi-line values.`,
  definitionFile: "agent.toml",
  // Codex identifies a subagent by the TOML `name`, not the filename — pin it.
  normalizeDefinition: (def, ctx) => setTomlName(def, ctx.slug),
  installScript: (ctx) => `# Install the Codex subagent into a project's .codex/agents/.
# Usage: bash install.sh [project-dir]   (defaults to the current directory)
DEST="\${1:-$PWD}/.codex/agents"
mkdir -p "$DEST"
install_file "$HERE/agent.toml" "$DEST/${ctx.slug}.toml"
echo "Installed ${ctx.slug}.toml to $DEST/"
echo "For a personal (global) agent, copy it to ~/.codex/agents/${ctx.slug}.toml instead."`,
  activationGuide: (ctx) => `# ${ctx.slug} — Codex subagent

Generated by Nightwriter from the prompt:

> ${ctx.userPrompt.trim()}

The definition is **\`agent.toml\`** (a Codex subagent). Codex subagents live in
\`.codex/agents/\` (project) or \`~/.codex/agents/\` (personal).

## Install
\`\`\`bash
bash install.sh            # into ./.codex/agents/
\`\`\`
Copies \`agent.toml\` to \`<project>/.codex/agents/${ctx.slug}.toml\`.

## Activate
Codex identifies a subagent by the \`name\` field **inside \`agent.toml\`** (not
the filename); Nightwriter pins it to **\`${ctx.slug}\`**. Start \`codex\` and say
e.g. "Use the ${ctx.slug} agent to …"; \`/agent\` switches between agent threads.
Adjust the \`model\` in the TOML to one your Codex account can use.
`,
};

/** OpenClaw agent workspace: a directory of bootstrap files + skills. */
const openclaw: TargetSpec = {
  id: "openclaw",
  displayName: "OpenClaw",
  formatInstructions: `An OpenClaw agent is a WORKSPACE of several Markdown files, not one
file. Output multiple files, each introduced by a delimiter line on its own:

===== FILE: <relative/path> =====

Produce exactly these files (in this order):

===== FILE: AGENTS.md =====
Operating instructions: the agent's mission, a numbered default workflow, and
safety rules (e.g. never leak secrets; ask before destructive actions).

===== FILE: SOUL.md =====
Persona: name, tone, communication style, and boundaries.

===== FILE: IDENTITY.md =====
A short identity block:
name: <Display Name>
theme: <one-line theme>
emoji: <a single emoji>

===== FILE: USER.md =====
A brief user-profile template (preferences, language, recurring needs).

===== FILE: TOOLS.md =====
Tool/CLI usage conventions and environment notes for this agent.

===== FILE: skills/<kebab-skill-name>/SKILL.md =====
One example skill with YAML frontmatter:
---
name: <kebab-skill-name>
description: <one sentence>
---
<a focused workflow for one task this agent does>

Output ONLY these files with the delimiter lines. No extra commentary or fences.`,
  definitionFile: "AGENTS.md",
  expandDefinition: (definition) => parseDelimitedFiles(definition, "workspace/", "AGENTS.md"),
  installScript: (ctx) => `# Install the OpenClaw agent workspace.
SRC="$HERE/workspace"
[ -d "$SRC" ] || { echo "error: workspace/ not found in archive: $SRC" >&2; exit 1; }
DEST="\${OPENCLAW_HOME:-$HOME/.openclaw}/workspace-${ctx.slug}"
[ -d "$DEST" ] && echo "note: updating existing workspace at $DEST"
mkdir -p "$DEST"
cp -R "$SRC/." "$DEST/"
echo "Workspace installed at $DEST"
echo
echo "Register the agent (set a model your provider supports):"
echo "  openclaw agents add ${ctx.slug} --workspace \\"$DEST\\" --model openai/gpt-5.5 --non-interactive"
echo "Optionally bind a channel, e.g.:"
echo "  openclaw agents bind --agent ${ctx.slug} --bind telegram:${ctx.slug}"
echo "Then: openclaw gateway restart && openclaw agents list --bindings"`,
  activationGuide: (ctx) => `# ${ctx.slug} — OpenClaw agent workspace

Generated by Nightwriter from the prompt:

> ${ctx.userPrompt.trim()}

OpenClaw agents are a **workspace** of bootstrap files (injected as project
context on each session) plus \`skills/\`. This archive's \`workspace/\` holds
\`AGENTS.md\`, \`SOUL.md\`, \`IDENTITY.md\`, \`USER.md\`, \`TOOLS.md\`, and an
example skill.

## Install
\`\`\`bash
bash install.sh
\`\`\`
Copies \`workspace/\` to \`$OPENCLAW_HOME/workspace-${ctx.slug}\` (defaults to
\`~/.openclaw\`) and prints the registration commands.

## Register & activate
\`\`\`bash
openclaw agents add ${ctx.slug} --workspace ~/.openclaw/workspace-${ctx.slug} --model openai/gpt-5.5 --non-interactive
openclaw agent --agent ${ctx.slug} --message "intro yourself"   # quick test
\`\`\`
Bind a Telegram/Discord/etc. account to route messages to this agent, and
consider enabling sandboxing for agents that run shell commands.
`,
};

/** Hermes Agent skill: a SKILL.md (agentskills.io-compatible). */
const hermes: TargetSpec = {
  id: "hermes",
  displayName: "Hermes Agent",
  formatInstructions: `A Hermes Agent capability is a SKILL.md: Markdown with YAML
frontmatter (agentskills.io-compatible).

---
name: <kebab-case-name>          # required
description: "<one sentence: when to use this skill>"   # required
version: 1.0.0
license: MIT
platforms: [linux, macos]
metadata:
  hermes:
    tags: [Tag1, Tag2]
---

# <Skill Title>

<short intro>

## Quick Reference
| Action | Command |
|--------|---------|
| ...    | ...     |

## Steps
1. ...
2. ...

Output ONLY the SKILL.md contents (valid YAML frontmatter + Markdown body).`,
  definitionFile: "SKILL.md",
  // The skill is invoked as /<name>; pin the frontmatter `name` to the slug so
  // it matches the install dir and the `/${slug}` shown in the guide.
  normalizeDefinition: (def, ctx) => setFrontmatterName(def, ctx.slug),
  installScript: (ctx) => `# Install the Hermes skill into ~/.hermes/skills/.
DEST="\${HERMES_HOME:-$HOME/.hermes}/skills/${ctx.slug}"
mkdir -p "$DEST"
install_file "$HERE/SKILL.md" "$DEST/SKILL.md"
echo "Installed skill to $DEST/SKILL.md"
echo "Verify with: hermes skills list   (invoke in a session as /${ctx.slug})"`,
  activationGuide: (ctx) => `# ${ctx.slug} — Hermes Agent skill

Generated by Nightwriter from the prompt:

> ${ctx.userPrompt.trim()}

Hermes Agent (NousResearch/hermes-agent) authors capabilities as **skills** — a
\`SKILL.md\` (agentskills.io format). The definition is **\`SKILL.md\`**.

## Install
\`\`\`bash
bash install.sh
\`\`\`
Copies \`SKILL.md\` to \`$HERMES_HOME/skills/${ctx.slug}/SKILL.md\` (defaults to
\`~/.hermes\`).

## Activate
\`\`\`bash
hermes skills list          # confirm it is listed
# then in a Hermes session, invoke it as:  /${ctx.slug}
\`\`\`
`,
};

/** Google ADK: a Python package exporting root_agent (built by install.sh). */
const adk: TargetSpec = {
  id: "adk",
  displayName: "Google ADK",
  formatInstructions: `The file is Python for the Google Agent Development Kit (ADK).
Define a module-level variable named root_agent:

from google.adk.agents import Agent

root_agent = Agent(
    name="<snake_case_name>",          # a valid Python identifier (not "user")
    model="gemini-2.5-flash",          # a current Gemini model id
    description="<one sentence>",
    instruction="""<the system prompt / instructions>""",
    tools=[],                          # optional: plain Python functions
)

Output only valid Python.`,
  definitionFile: "agent.py",
  // `adk run <pkg>` resolves the agent by its package dir; pin the root_agent
  // `name=` to the same identifier so the two stay consistent.
  normalizeDefinition: (def, ctx) => setPyAgentName(def, toPyIdentifier(ctx.slug)),
  installScript: (ctx) => {
    const pkg = toPyIdentifier(ctx.slug);
    return `# Build the ADK package from agent.py and set up a venv.
PKG="${pkg}"
mkdir -p "$PKG"
install_file "$HERE/agent.py" "$PKG/agent.py"
printf 'from . import agent\\n' > "$PKG/__init__.py"
[ -f "$PKG/.env" ] || cp "$HERE/.env.example" "$PKG/.env"
python3 -m venv .venv
source .venv/bin/activate
pip install --upgrade pip
pip install -r "$HERE/requirements.txt"
echo "Installed. Set your key in $PKG/.env, then run:"
echo "  source .venv/bin/activate && adk run $PKG     # or: adk web"`;
  },
  activationGuide: (ctx) => {
    const pkg = toPyIdentifier(ctx.slug);
    return `# ${pkg} — Google ADK agent

Generated by Nightwriter from the prompt:

> ${ctx.userPrompt.trim()}

The definition is **\`agent.py\`** (exports \`root_agent\`). Requires Python ≥ 3.10.

## Install
\`\`\`bash
bash install.sh
\`\`\`
Builds the \`${pkg}/\` package (\`__init__.py\` + \`agent.py\` + \`.env\`), creates a
venv, and installs \`google-adk\`.

## Activate
\`\`\`bash
# set GOOGLE_API_KEY in ${pkg}/.env first (Google AI Studio key)
source .venv/bin/activate
adk run ${pkg}        # or: adk web   (dev UI at http://localhost:8000)
\`\`\`
The \`model\` id in \`agent.py\` may need updating to a current Gemini model.
`;
  },
  extraFiles: () => [
    { path: "requirements.txt", content: "google-adk>=2.0.0\n" },
    {
      path: ".env.example",
      content: "GOOGLE_GENAI_USE_VERTEXAI=FALSE\nGOOGLE_API_KEY=your-api-key-here\n",
    },
  ],
};

/* ------------------------------ helpers ------------------------------ */

function toSnake(slug: string): string {
  return slug.replace(/-/g, "_");
}

// Python keywords + ADK's reserved `user`; none may be used as an agent name.
const PY_RESERVED = new Set([
  "user", "False", "None", "True", "and", "as", "assert", "async", "await",
  "break", "class", "continue", "def", "del", "elif", "else", "except",
  "finally", "for", "from", "global", "if", "import", "in", "is", "lambda",
  "nonlocal", "not", "or", "pass", "raise", "return", "try", "while", "with",
  "yield",
]);

/**
 * A valid Python identifier from a slug: snake_case, with a leading underscore
 * when it would otherwise start with a digit (`2fa-agent` → `_2fa_agent`) or
 * collide with a Python keyword / ADK's reserved `user` (`class` → `_class`).
 */
function toPyIdentifier(slug: string): string {
  const snake = toSnake(slug);
  return /^[0-9]/.test(snake) || PY_RESERVED.has(snake) ? `_${snake}` : snake;
}

/**
 * Force the `name:` field inside a leading YAML frontmatter block to `name`.
 * No-op if the content has no frontmatter or no `name:` line (defensive: the
 * definition is LLM-generated and may not follow the requested shape).
 */
function setFrontmatterName(def: string, name: string): string {
  if (!def.startsWith("---")) return def;
  const close = def.indexOf("\n---", 3);
  if (close === -1) return def;
  const head = def.slice(0, close);
  if (!/^name:.*$/m.test(head)) return def;
  return head.replace(/^name:.*$/m, `name: ${name}`) + def.slice(close);
}

/** Force the first TOML `name = "…"` assignment to `name`. No-op if absent. */
function setTomlName(def: string, name: string): string {
  return def.replace(/^name\s*=\s*".*?"/m, `name = "${name}"`);
}

/**
 * Force the `name="…"` of the `root_agent = Agent(…)` call when it is the
 * first constructor argument (the documented format). Deliberately anchored to
 * `Agent(` immediately followed by `name=`, so a `name=` nested in an earlier
 * argument (e.g. a tool) is never corrupted; safely no-ops otherwise.
 */
function setPyAgentName(def: string, name: string): string {
  return def.replace(
    /(root_agent\s*=\s*Agent\(\s*)name\s*=\s*"[^"]*"/,
    `$1name="${name}"`,
  );
}

/**
 * Split a definition that uses `===== FILE: <path> =====` delimiters into
 * multiple files under `prefix`. Falls back to a single file when no delimiter
 * is present. (Paths are further sanitized for zip-slip by the factory.)
 */
function parseDelimitedFiles(
  definition: string,
  prefix: string,
  fallbackName: string,
): ArtifactFile[] {
  const re = /^=====\s*FILE:\s*(.+?)\s*=====\s*$/;
  const files: ArtifactFile[] = [];
  let current: ArtifactFile | null = null;
  for (const line of definition.split("\n")) {
    const m = re.exec(line.trim());
    if (m) {
      current = { path: prefix + m[1]!.trim(), content: "" };
      files.push(current);
      continue;
    }
    if (current) current.content += `${line}\n`;
  }
  const nonEmpty = files.filter((f) => f.content.trim().length > 0);
  if (nonEmpty.length === 0)
    return [{ path: prefix + fallbackName, content: definition }];
  return nonEmpty.map((f) => ({ path: f.path, content: f.content.trimEnd() }));
}

export const TARGET_SPECS: TargetSpec[] = [
  claude,
  codex,
  openclaw,
  hermes,
  adk,
];
